version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: adminTax
      POSTGRES_PASSWORD: admin!
      POSTGRES_DB: ktaxes
    volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
volumes:
    pgdata:
